package com.example.mochamadwiby.aplikasi;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.widget.ArrayAdapter;
import android.widget.AutoCompleteTextView;
import android.widget.MultiAutoCompleteTextView;


public class Presentasi extends AppCompatActivity {
    AutoCompleteTextView actv;
    MultiAutoCompleteTextView mactv;
    String[] hewan={
            "alap alap",
            "angsa",
            "anjing",
            "anoa",
            "antelop",
            "arwana",
            "ayam",
            "ayam kalkun",
            "ayam kate",
            "babi",
            "badak",
            "bajing",
            "bangau",
            "bangsat",
            "banteng",
            "bebek",
            "bekantan",
            "bekicot",
            "belalang",
            "belatung (larva lalat)",
            "belibis",
            "belut",
            "beo",
            "berang berang",
            "beruang",
            "beruk",
            "beruk",
            "betet",
            "betok",
            "biawak",
            "bintang laut",
            "biribiri",
            "bison",
            "blekok",
            "buaya",
            "bulu babi",
            "bunglon",
            "burung",
            "burung gereja",
            "burung hantu",
            "burung unta",
            "cacing",
            "camar",
            "capung",
            "cencorang",
            "cendrawasih",
            "cere",
            "cerek",
            "cheetah",
            "cicak",
            "codot",
            "cucakrawa",
            "cumicumi",
            "dara",
            "domba",
            "duyung",
            "elang",
            "entok",
            "gabus",
            "gagak",
            "gajah",
            "gapih",
            "garuda",
            "gelatik",
            "gorila",
            "gurame",
            "gurita",
            "hamster",
            "harimau",
            "hiena",
            "hiu",
            "iguana",
            "ikan",
            "itik",
            "jalak",
            "jangkrik",
            "jerapah",
            "kadal",
            "kakatua",
            "kaki seribu",
            "kalajengking",
            "kalkun",
            "kalong",
            "kambing",
            "kampret",
            "kangguru / kanguru",
            "kapibara",
            "kasuari",
            "katak",
            "kebo",
            "kecebong (larva kodok)",
            "kecoa",
            "kecoak",
            "kelabang",
            "keledai",
            "kelelawar",
            "kelinci",
            "kenari",
            "keong",
            "kepiting",
            "kera",
            "kerang",
            "kerapu",
            "kerbau",
            "kijang",
            "koala",
            "kobra",
            "kodok",
            "koi",
            "koi",
            "komodo",
            "kucing",
            "kuda",
            "kudanil",
            "kudaponi",
            "kumbang",
            "kupu kupu",
            "kura kura",
            "kuskus",
            "kutu",
            "labalaba",
            "lalat",
            "lalatbuah",
            "laler",
            "landak",
            "landaklaut",
            "laron",
            "lebah",
            "lele",
            "lemur",
            "lintah",
            "lipan",
            "lipas",
            "lobster",
            "lumbalumba",
            "lutung",
            "lutung",
            "luwak",
            "macan",
            "macankumbang",
            "macantutul",
            "makarel",
            "maleo",
            "mambruk",
            "marmut",
            "maskoki",
            "merak",
            "merpati",
            "milkat",
            "monyet",
            "mujaer",
            "musang",
            "ngengat",
            "nila",
            "nyamuk",
            "ngengat",
            "nila",
            "nyamuk",
            "panda",
            "parkit",
            "patin",
            "paus",
            "pelatuk",
            "penyu",
            "perkutut",
            "pesut",
            "pinguin",
            "pipit",
            "piranha",
            "piton",
            "rajawali",
            "rayap",
            "rubah",
            "rusa",
            "salmon",
            "sanca",
            "sapi",
            "sapu sapu",
            "semut",
            "sepat",
            "serigala",
            "siamang",
            "singa",
            "siput",
            "soang",
            "sotong",
            "tangkasi",
            "tapir",
            "tarantula",
            "tarsius",
            "tawon",
            "tekukur",
            "tengiri",
            "teri",
            "teripang",
            "terwelu",
            "tikus",
            "tiram",
            "todak",
            "tomcat",
            "trenggiling",
            "tuna",
            "tupai",
            "uburubur",
            "udang",
            "ular",
            "ularderik",
            "ularsendok",
            "ulat",
            "undurundur",
            "unta",
            "walet",
            "wauwau",
            "wereng",
            "yuyu",
            "zebra",
    };

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_presentasi);

        actv=(AutoCompleteTextView)findViewById(R.id.autoCompleteTextView);
        mactv=(MultiAutoCompleteTextView)findViewById(R.id.multiAutoCompleteTextView);

        ArrayAdapter adapter = new ArrayAdapter(this,android.R.layout.simple_list_item_1,hewan);

        actv.setAdapter(adapter);
        mactv.setThreshold(1);

        actv.setAdapter(adapter);
        mactv.setTokenizer(new MultiAutoCompleteTextView.CommaTokenizer());
    }
}


